include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_single_quotes: false
    prefer_constructors_over_static_methods: false
    sort_pub_dependencies: false
analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
  errors:
    invalid_annotation_target: ignore