name: raven_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  web_socket_channel: ^2.4.5

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/svgs/
   - assets/pngs/

  fonts:
   - family: Satoshi
     fonts:
       - asset: assets/fonts/Satoshi-Bold.otf
         weight: 500
       - asset: assets/fonts/Satoshi-Medium.otf
         weight: 700